%% Random walk
close all
clear
dbstop if error

n_time_step=100;
t=1:n_time_step;
on=ones(1,n_time_step);

width=1;
height=.3;
X0=[5 5 ];

%%
%    figure(1)
    figure('Units','inches',...
        'Position',[X0(1) X0(2) width height],...
        'PaperPositionMode','auto');
   plot(t,on,'r');
%    set(gca,'visible','off')
   set(gca,'XtickLabel',[],'YtickLabel',[],'Xtick',[],'Ytick',[]);
%     set(gca,...
%         'Units','normalized',...
%         'FontUnits','points',...
%         'FontWeight','normal',...
%         'FontSize',8,...
%         'FontName','Times')
    title('Stochastic',...
        'interpreter','latex',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',7,...
        'FontName','Times')
%     axis(ax)
%     eval( ['print -depsc -loose one_sample.eps']);
    print -depsc -loose legend_r.eps
%%
%    figure(1)
    figure('Units','inches',...
        'Position',[X0(1) X0(2) width height],...
        'PaperPositionMode','auto');
   plot(t,on,'b');
%    set(gca,'visible','off')
   set(gca,'XtickLabel',[],'YtickLabel',[],'Xtick',[],'Ytick',[]);
%     set(gca,...
%         'Units','normalized',...
%         'FontUnits','points',...
%         'FontWeight','normal',...
%         'FontSize',8,...
%         'FontName','Times')
    title('Deterministic',...
        'interpreter','latex',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',7,...
        'FontName','Times')
%     axis(ax)
%     eval( ['print -depsc -loose one_sample.eps']);
    print -depsc -loose legend_b.eps
%%
%    figure(1)
    figure('Units','inches',...
        'Position',[X0(1) X0(2) width height],...
        'PaperPositionMode','auto');
   plot(t,on,'g.');
%    set(gca,'visible','off')
   set(gca,'XtickLabel',[],'YtickLabel',[],'Xtick',[],'Ytick',[]);
%     set(gca,...
%         'Units','normalized',...
%         'FontUnits','points',...
%         'FontWeight','normal',...
%         'FontSize',8,...
%         'FontName','Times')
    title('Eddy Viscosity',...
        'interpreter','latex',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',7,...
        'FontName','Times')
%     axis(ax)
%     eval( ['print -depsc -loose one_sample.eps']);
    print -depsc -loose legend_g.eps
%%
%    figure(1)
    figure('Units','inches',...
        'Position',[X0(1) X0(2) width height],...
        'PaperPositionMode','auto');
   plot(t,on,'.k');
%    set(gca,'visible','off')
   set(gca,'XtickLabel',[],'YtickLabel',[],'Xtick',[],'Ytick',[]);
%     set(gca,...
%         'Units','normalized',...
%         'FontUnits','points',...
%         'FontWeight','normal',...
%         'FontSize',8,...
%         'FontName','Times')
    title('Real values',...
        'interpreter','latex',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',7,...
        'FontName','Times')
%     axis(ax)
%     eval( ['print -depsc -loose one_sample.eps']);
    print -depsc -loose legend_k.eps
%%
    