

param.file_nrj_mU=[ param.folder_results '_nrj_mU_' ...
    param.type_data '0.mat'];
if exist(param.file_nrj_mU,'file')==2
    load(param.file_nrj_mU, 'nrj_mU');
else
    type_data_mU=[param.type_data num2str(0)];
    param.name_file_mU=[param.folder_data type_data_mU '_U_centered'];
    load(param.name_file_mU,'m_U');
    
    switch param.type_data
        case {'incompact3d_wake_episode3_cut_truncated',...
                'incompact3D_noisy2D_40dt_subsampl',...
                'incompact3D_noisy2D_40dt_subsampl_truncated',...
                'inc3D_Re300_40dt_blocks', 'inc3D_Re300_40dt_blocks_truncated', 'inc3D_Re300_40dt_blocks_test_basis',...
                'inc3D_Re3900_blocks', 'inc3D_Re3900_blocks_truncated', 'inc3D_Re3900_blocks_test_basis',...
                'DNS300_inc3d_3D_2017_04_02_blocks', 'DNS300_inc3d_3D_2017_04_02_blocks_truncated',...
                'DNS300_inc3d_3D_2017_04_02_blocks_test_basis',...
                'test2D_blocks', 'test2D_blocks_truncated', 'test2D_blocks_test_basis',...
                'small_test_in_blocks', 'small_test_in_blocks_truncated',...
                'small_test_in_blocks_test_basis',...
                'DNS100_inc3d_2D_2018_11_16_blocks',...
                'DNS100_inc3d_2D_2018_11_16_blocks_truncated',...
                'DNS100_inc3d_2D_2018_11_16_blocks_test_basis',...
                'DNS300_inc3d_3D_2017_04_02_NOT_BLURRED_blocks',...
                'DNS300_inc3d_3D_2017_04_02_NOT_BLURRED_blocks_truncated',...
                'DNS300_inc3d_3D_2017_04_02_NOT_BLURRED_blocks_test_basis',...
                'inc3D_HRLESlong_Re3900_blocks',...
                'inc3D_HRLESlong_Re3900_blocks_truncated',...
                'inc3D_HRLESlong_Re3900_blocks_test_basis'}
            m_U(:,:,1)=m_U(:,:,1)-1;
        otherwise
            warning('No wake flow????')
    end
    nrj_mU = sum(m_U(:).^2)*prod(param.dX);
    param.file_nrj_mU=[ param.folder_results '_nrj_mU_' param.type_data '.mat'];
    mkdir(param.folder_results)
    save(param.file_nrj_mU, 'nrj_mU');
end

% %     param.name_file_pre_c = [param.folder_data param.type_data '_pre_c'];
% %     param_ref=param;
% %     load(param.name_file_pre_c,'c','param');
% %     param_c = param; param=param_ref;clear param_ref;
% %     c=c*prod(param.dX)/param_c.N_tot;
% %     nrj_varying_tot=trace(c);
% nrj_varying_tot = trace(c)*prod(param.dX)/param.N_tot;
% lambda_ = lambda*prod(param.dX)/param.N_tot;
nrj_varying_tot = trace(c);
lambda_ = lambda;
lambda_ =[ nrj_mU lambda_(1:end-1)' ];
Volume = prod(param.MX .* param.dX );

% Quantity of energy represented by nb_modes Chronos
nrj_tot = nrj_mU + nrj_varying_tot;
lambda_ = lambda_ / nrj_tot ;
k_=0:(length(lambda_)-1);

% el=cumsum(lambda(1:nb_modes))/trace_c;

%% Plot
LineWidth = 1;
FontSize = 10;
FontSizeTtitle = 11;
color_sexy(1,:) = [0.8500, 0.3250, 0.0980];
color_sexy(2,:) = [0.9290, 0.6940, 0.1250];
color_sexy(3,:) = [0.4940, 0.1840, 0.5560];
color_sexy(4,:) = [0.4660, 0.6740, 0.1880] 	;
color_sexy(5,:) = [0.3010, 0.7450, 0.9330];
color_sexy(6,:) = [0.6350, 0.0780, 0.1840];
Color3=[0.0 0.5 0.0];

width=2;
height=1;
height = height*3/2;


figure1=figure(1);
close(figure1)
figure('Units','inches', ...
    'Position',[0 0 width height], ...
    'PaperPositionMode','auto');

loglog(k_,lambda_,'o-')

set(gca,...
    'XGrid','on', ...
    'YGrid','on', ...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',FontSize,...
    'FontName','Times')
ylabel('norm. $\lambda_k$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',FontSize,...
    'FontName','Times')
xlabel('$k$',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',FontSize,...
    'FontName','Times')
% title(['$n=' num2str(param.nb_modes) '$'],...
%     'FontUnits','points',...
%     'FontWeight','normal',...
%     'interpreter','latex',...
%     'FontSize',FontSizeTtitle,...
%     'FontName','Times')
% ax=axis;
ax=[ 1 1279 1e-6 1];
axis(ax);

drawnow;
eval( ['print -dpng ' param.folder_results ...
    param.type_data '_' ...
    'lambda_decrease.png']);
keyboard;
