function param = fct_name_file_diffusion_mode_PIV(param)
% Create the name of the file whe the diffusion mode(s) are saved
%

% Name of the saving file
if param.a_time_dependant
    dependance_on_time_of_a = '_a_time_dependant_';
else
    dependance_on_time_of_a = '_a_cst_';
end

str_threshold = num2str(param.decor_by_subsampl.spectrum_threshold);
i_str_threshold = (str_threshold == '.');
str_threshold(i_str_threshold)='_';
%     str_threshold = num2str(param.decor_by_subsampl.spectrum_threshold);
param.name_file_diffusion_mode_PIV =  ...
    [param.folder_data 'diffusion_mode_PIV_' param.type_data '_' ...
    num2str(param.nb_modes) '_modes' ...
    dependance_on_time_of_a ...
    'threshold_' str_threshold ];
param.name_file_diffusion_mode_PIV = ...
    [param.name_file_diffusion_mode_PIV '.mat'];

% param.name_file_HSigSigH_PIV =  ...
%     [param.folder_data 'HSigSigH_PIV_' param.type_data '_' ...
param.name_file_HSigSigH_PIV =  ...
    [param.folder_data(1:end-1) '_PIV\' 'HSigSigH_PIV_' param.type_data '_' ...
    num2str(param.nb_modes) '_modes' ...
    dependance_on_time_of_a ...
    'threshold_' str_threshold ];
param.name_file_HSigSigH_PIV = ...
    [param.name_file_HSigSigH_PIV '.mat'];

% if isfield(param,'N_estim')
%     param.name_file_diffusion_mode_PIV = ...
%         [ param.name_file_diffusion_mode_PIV ...
%         '_p_estim_' num2str(param.period_estim)];
% end
